version: 2
jobs:
  build:
    docker:
      - image: banian/node
    working_directory: /usr/src/app
    branches:
      ignore:
        - master
    steps:
      # Add github ssh deploy key
      - add_ssh_keys:
          fingerprints:
            - "3a:eb:d4:d2:60:ac:45:b6:92:d9:40:e2:10:a9:f1:c8"

      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Disable yarn progress bar for perf
      - run:
          command: yarn config set no-progress

      # Greenkeeper-lockfile
      - run:
          name: Installing Greenkeeper-lockfile
          command: yarn global add greenkeeper-lockfile@1

      # Install dependencies
      - run:
          name: Installing Dependencies
          command: yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Update yarn.lock
      - run:
          name: Updating lockfile
          command: greenkeeper-lockfile-update

      # Test
      - run:
          name: Tests
          command: yarn test

      # Build
      - run:
          name: Building phenomic site
          command: yarn build

      # Upload yarn.lock
      - run:
          name: Uploading lockfile
          command: greenkeeper-lockfile-upload

  deploy:
    docker:
      - image: banian/node
    working_directory: /usr/src/app
    steps:
      # Deploy to github pages
      - deploy:
          name: Deploying src branch to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI

            git clone $CIRCLE_REPOSITORY_URL out

            cd out
            git checkout --orphan master
            git rm -rf .
            cd ..

            cp -a dist/. out/.

            mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
            cd out

            echo "medfreeman.io" > CNAME

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            git push --force origin master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: src
